blank_issues_enabled: true
contact_links:
  - name: Testcoin Core Security Policy
    url: https://github.com/testcoin/testcoin/blob/master/SECURITY.md
    about: View security policy
  - name: Testcoin Core Developers
    url: https://testcoincore.org
    about: Testcoin Core homepage
